// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGj35dV70CVpkMMzoXQ9QP-MV1e6p4cqo',
    appId: '1:22258914724:web:333ac4f34f370a5f079d31',
    messagingSenderId: '22258914724',
    projectId: 'fm-application',
    authDomain: 'fm-application.firebaseapp.com',
    storageBucket: 'fm-application.firebasestorage.app',
    measurementId: 'G-WRKJXJ0H25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOIGm4gaUg0ku3wnMo7vnoz1upoPgIaRo',
    appId: '1:22258914724:android:8b052acb57268170079d31',
    messagingSenderId: '22258914724',
    projectId: 'fm-application',
    storageBucket: 'fm-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCINFUTq2FLzE4BgeViKbUU8vHoEJmZHA',
    appId: '1:22258914724:ios:bcdff87d98246ea0079d31',
    messagingSenderId: '22258914724',
    projectId: 'fm-application',
    storageBucket: 'fm-application.firebasestorage.app',
    iosBundleId: 'com.example.acilityManagementApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCINFUTq2FLzE4BgeViKbUU8vHoEJmZHA',
    appId: '1:22258914724:ios:bcdff87d98246ea0079d31',
    messagingSenderId: '22258914724',
    projectId: 'fm-application',
    storageBucket: 'fm-application.firebasestorage.app',
    iosBundleId: 'com.example.acilityManagementApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGj35dV70CVpkMMzoXQ9QP-MV1e6p4cqo',
    appId: '1:22258914724:web:8844f58b2737cac8079d31',
    messagingSenderId: '22258914724',
    projectId: 'fm-application',
    authDomain: 'fm-application.firebaseapp.com',
    storageBucket: 'fm-application.firebasestorage.app',
    measurementId: 'G-JP433DM61Y',
  );
}
